### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by sorgelig** [MiSTer-devel/Arcade-Rygar_MiSTer#1]
Hi!

You need to create "releases" folder and put Arcade-Rygar_YYMMDD.rbf together with mra there, so Updater will be able to download it.

**Comment by nullobject** [comment]
Hi @sorgelig, happy to sort that out.

Long term, do you have any thoughts about using GitHub releases for the MiSTer updater?

I just posted something on the Atari Forum if you would prefer to discuss it there.

Thanks.

**Comment by sorgelig** [comment]
In short - it's not convenient for development.
Sometime i need to travel back in releases, so i have releases folder where i can quickly pick different versions. In commits history i also see at which point particular release has been made.
There are some other may be not obvious inconveniences. 
At the end GitHub release feature is not integrated into git. It's feature living separately.

**Comment by halfmanhalftaco** [comment]
releases is a separate feature because git is source code control, not binary artifact control. tags & releases is way more elegant than a separate commit and binary blobs in git.

**Comment by nullobject** [comment]
@sorgelig Fair enough, and thanks for your thoughts. Closing this issue.
